### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by brandonlehmann** [coinlegacycore/coinlegacy#1]
Hi there, you seem to be missing the proper LICENSE file and attribution of the source of the files found in this repo. If you need help rectifying this, please let me know.

**Comment by coinlegacycore** [comment]
> Hi there, you seem to be missing the proper LICENSE file and attribution of the source of the files found in this repo. If you need help rectifying this, please let me know.

Thanks for pointing it. Reupload the missing LICENSE.
